_BASE_: "../base-finetune.yaml"
RUN_N_TIMES: 100
DATA:
  NAME: "pvtg"
  DATAPATH: "Datasets/PV_Tomato_gray2"   #TODO: need to specify here
  NUMBER_CLASSES: 1
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001