_BASE_: "../base-linear.yaml"
RUN_N_TIMES: 100
DATA:
  NAME: "cotton"
  DATAPATH: "Datasets/Cotton_plant_disease"   #TODO: need to specify here
  NUMBER_CLASSES: 1
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001